apiVersion: v1
kind: ServiceAccount
metadata:
  name: estore-account
  labels:
    account: account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
        version: v1
    spec:
      serviceAccountName: estore-account
      containers:
        - name: account
          image: account-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: account-config
          securityContext:
            runAsUser: 1000