apiVersion: v1
kind: Service
metadata:
  name: product-service # Sets service name
  labels:
    app: product-service # Labels and Selectors
    version: v1
spec:
  type: ClusterIP # Sets service type
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084
  selector:
    app: product-service