spring:
  application:
    name: shipment-service

server:
  port: 8082
  error:
    include-message: always

custom:
  account-service: ${ACCOUNT_SERVICE:http://localhost:8081}
  order-service: ${ORDER_SERVICE:http://localhost:8081}
