spring:
    application:
        name: bank-service

server:
    port: 8087
    error:
        include-message: always

custom:
    account-service: ${ACCOUNT_SERVICE:http://localhost:8081}
    order-service: ${ORDER_SERVICE:http://localhost:8081}