spring:
  application:
    name: payment-service

server:
  port: 8085
  error:
    include-message: always

custom:
  account-service: ${ACCOUNT_SERVICE:http://localhost:8081}
  order-service: ${ORDER_SERVICE:http://localhost:8083}
  credit-service: ${CREDIT_SERVICE:http://localhost:8085}
  paypal-service: ${PAYPAL_SERVICE:http://localhost:8085}
  bank-service: ${BANK_SERVICE:http://localhost:8085}