version: '3.8'
services:
  consul:
    container_name: consul
    image: consul
    ports:
      - 8500:8500
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
  db1:
    container_name: db1.yml
    image: postgres
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  account-service:
    container_name: product-service.yml
    image: account-service:latest
    deploy:
      mode: replicated
      replicas: 2
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms64m
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_DATASOURCE_URL: jdbc:postgresql://db1.yml:5432/account